package com.conner.assistant.utils;

import org.springframework.ai.document.Document;
import org.springframework.ai.vectorstore.SearchRequest;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.Date;
import java.util.List;

@Component
public class OllamaUtility {

    @Autowired
    private VectorStore vectorStore;

    private final static String SYSTEM_INSTRUCTION = "You're an agent working for webdevbuilders.";

    private final StringBuilder chatHistory = new StringBuilder("chat history :");

    private int messageCounter = 1;

    /**
     * Generates a chat template for the llama3 AI model.
     *
     * @param prompt the input prompt string
     * @return a chat template for the llama assistant
     */
    public String llamaChatTemplate(String prompt) {
        return "<|start_header_id|>system<|end_header_id|>" + SYSTEM_INSTRUCTION + "<|eot_id|> " +
                "<|start_header_id|>messages<|end_header_id|>" + chatHistory + "<|eot_id|>" +
                "<|start_header_id|>context<|end_header_id|>" + generateContext(prompt) + "<|eot_id|> " +
                "<|start_header_id|>user<|end_header_id|>" + prompt + "<|eot_id|> " +
                "<|start_header_id|>assistant<|end_header_id|> provide information <|eot_id|> " +
                "<|start_header_id|>response<|end_header_id|>";
    }

    /**
     * Builds the chat history for the llama3 AI model.
     *
     * @param prompt         the user's input prompt string
     * @param llama3Response the response generated by llama3 AI model
     */
    public void chatHistoryBuilder(String prompt, String llama3Response) {
        chatHistory.append("Message ").append(messageCounter).append(" = [");
        chatHistory.append("{user : content = ").append(prompt).append("},\n");
        chatHistory.append("{system : content = ").append(llama3Response).append("}\n");
        chatHistory.append("]\n");
        messageCounter++;
    }

    //Adapt code when needed or split method
    private String generateContext(String prompt) {
        StringBuilder contextStringBuilder = new StringBuilder();

        List<Document> documents = vectorStore.similaritySearch(SearchRequest.defaults()
                .withTopK(4)
                .withSimilarityThreshold(0.3)
                .withQuery(prompt)
        );

        for (int i = 0; i < documents.size(); i++) {
            contextStringBuilder.append("Retrieved document ")
                    .append(i)
                    .append(" { ")
                    .append(documents.get(i).getContent())
                    .append(" }\n");
        }

        return contextStringBuilder.toString();
    }

}